import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { MermaidGeneratedSharedModule, EventModelingGeneratedModule } from '../generated/module.js';
import { EventModelingTokenBuilder } from './tokenBuilder.js';
import { EventModelingValueConverter } from './valueConverter.js';

/**
 * Declaration of `EventModeling` services.
 */
interface EventModelingAddedServices {
  parser: {
    TokenBuilder: EventModelingTokenBuilder;
    ValueConverter: EventModelingValueConverter;
  };
}

/**
 * Union of Langium default services and `EventModeling` services.
 */
export type EventModelingServices = LangiumCoreServices & EventModelingAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `EventModeling` services.
 */
export const EventModelingModule: Module<
  EventModelingServices,
  PartialLangiumCoreServices & EventModelingAddedServices
> = {
  parser: {
    TokenBuilder: () => new EventModelingTokenBuilder(),
    ValueConverter: () => new EventModelingValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createEventModelingServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  EventModeling: EventModelingServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const EventModeling: EventModelingServices = inject(
    createDefaultCoreModule({ shared }),
    EventModelingGeneratedModule,
    EventModelingModule
  );
  shared.ServiceRegistry.register(EventModeling);
  return { shared, EventModeling };
}
